"""
圣杯牌组 - Cups (14张)
元素：水 | 代表：情感、直觉、共情、关系
对应星座：巨蟹、天蝎、双鱼
"""

CUPS = [
    {
        "number": 1,
        "name": "圣杯王牌 Ace of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "新的情感、爱的萌芽、直觉涌现、内心充盈",
        "reversed": "情感封闭、爱意受阻、内心空虚、直觉迟钝",
        "upright_love": "新恋情降临，心中涌起强烈的爱意，情感连接深刻",
        "reversed_love": "对感情关上心门，害怕受伤不愿敞开自己",
        "upright_work": "对工作充满热爱，新项目带来情感满足，创意灵感涌现",
        "reversed_work": "对工作失去热情，感到空虚无意义，缺乏情感投入",
    },
    {
        "number": 2,
        "name": "圣杯二 Two of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "相互吸引、伙伴关系、心灵连接、平等交流",
        "reversed": "关系失衡、沟通断裂、互不理解、分离分手",
        "upright_love": "两情相悦心灵契合，关系平等互相尊重，甜蜜恋爱",
        "reversed_love": "感情失衡一方付出多，沟通出问题，面临分离",
        "upright_work": "找到好的合作伙伴，双方默契配合，互利共赢",
        "reversed_work": "合作关系出现裂痕，理念不合，伙伴关系破裂",
    },
    {
        "number": 3,
        "name": "圣杯三 Three of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "欢庆聚会、友情支持、团体和谐、分享喜悦",
        "reversed": "社交疲惫、圈子矛盾、过度放纵、三角关系",
        "upright_love": "朋友祝福的感情，社交中遇到心仪对象，三人行的快乐",
        "reversed_love": "第三者介入的风险，朋友圈影响感情，社交中的暧昧",
        "upright_work": "团队合作愉快，项目庆功，同事关系融洽",
        "reversed_work": "办公室小团体矛盾，过度社交影响工作，团队不和",
    },
    {
        "number": 4,
        "name": "圣杯四 Four of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "冷漠无感、不满足、沉思内省、忽视机会",
        "reversed": "重新振作、抓住机会、走出低迷、感恩珍惜",
        "upright_love": "对感情麻木无感，身在福中不知福，忽视对方的好",
        "reversed_love": "重新发现对方的好，走出情感低谷，珍惜眼前人",
        "upright_work": "对工作感到厌倦，眼前有机会却看不到，缺乏动力",
        "reversed_work": "走出倦怠期，重新发现工作的意义，抓住新机会",
    },
    {
        "number": 5,
        "name": "圣杯五 Five of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "悲伤失落、遗憾后悔、只看失去、沉浸悲痛",
        "reversed": "走出悲伤、接受现实、看到希望、放下遗憾",
        "upright_love": "感情中的伤痛和遗憾，只看到失去的忽略还拥有的",
        "reversed_love": "从失恋中走出来，接受结果，准备好迎接新感情",
        "upright_work": "项目失败后沉浸在失落中，只关注损失忽视机会",
        "reversed_work": "从失败中恢复，吸取教训重新出发，看到新可能",
    },
    {
        "number": 6,
        "name": "圣杯六 Six of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "童年回忆、纯真美好、旧人重逢、怀旧温馨",
        "reversed": "活在过去、不切实际的怀旧、成长之痛、放不下",
        "upright_love": "初恋般的纯真感情，旧情人重逢，温馨甜蜜的回忆",
        "reversed_love": "沉溺于过去的感情无法前进，用过去标准衡量现在",
        "upright_work": "回归初心找到工作热情，老客户回来，与旧同事合作",
        "reversed_work": "沉迷过去的辉煌不愿面对现实，怀旧心态阻碍进步",
    },
    {
        "number": 7,
        "name": "圣杯七 Seven of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "幻想迷雾、选择太多、白日梦、诱惑陷阱",
        "reversed": "回归现实、做出选择、看清真相、脚踏实地",
        "upright_love": "对感情有不切实际的幻想，选择太多反而迷失",
        "reversed_love": "看清感情真相，不再幻想，做出务实的选择",
        "upright_work": "选择太多眼花缭乱，沉迷空想不付诸行动",
        "reversed_work": "从空想回到现实，明确目标专注执行",
    },
    {
        "number": 8,
        "name": "圣杯八 Eight of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "主动离开、追寻内心、放下已有、寻找更深意义",
        "reversed": "害怕离开、随波逐流、不愿放手、逃避内心",
        "upright_love": "主动离开不再满足的关系，追寻真正想要的感情",
        "reversed_love": "明知不合适却不舍得离开，害怕孤独将就凑合",
        "upright_work": "离开不再满足的工作去追求真正热爱的事",
        "reversed_work": "在不喜欢的工作中将就，没有勇气做出改变",
    },
    {
        "number": 9,
        "name": "圣杯九 Nine of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "心愿达成、满足感、享受成果、幸福快乐",
        "reversed": "贪心不足、虚荣炫耀、内心空虚、物质主义",
        "upright_love": "感情中心愿达成，满足幸福的状态，如愿以偿",
        "reversed_love": "对感情期望过高永远不满足，用物质衡量爱情",
        "upright_work": "工作目标达成，享受努力的成果，心满意足",
        "reversed_work": "取得成绩后骄傲自满，过度追求物质回报忽略初心",
    },
    {
        "number": 10,
        "name": "圣杯十 Ten of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "家庭幸福、情感圆满、和谐美满、长久之爱",
        "reversed": "家庭矛盾、关系破裂、理想与现实落差、不和谐",
        "upright_love": "感情圆满幸福，家庭和睦，长久稳定的爱情",
        "reversed_love": "家庭矛盾频发，理想中的爱情与现实差距大",
        "upright_work": "团队如家般和谐，事业与生活平衡，工作带来幸福感",
        "reversed_work": "工作影响家庭关系，团队不和，对工作环境不满",
    },
    {
        "number": 11,
        "name": "圣杯侍从 Page of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "情感萌芽、浪漫天真、创意灵感、好消息",
        "reversed": "情绪化、不成熟、幻想过多、逃避现实",
        "upright_love": "初恋般的心动，纯真浪漫的表白，收到爱的信号",
        "reversed_love": "对感情过于幼稚天真，情绪化让对方难以招架",
        "upright_work": "有创意新想法，收到好消息，用直觉解决问题",
        "reversed_work": "想法不成熟难以落地，情绪影响工作表现",
    },
    {
        "number": 12,
        "name": "圣杯骑士 Knight of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "浪漫追求、温柔体贴、带着爱意前行、理想主义",
        "reversed": "不切实际、花言巧语、情感操控、逃避承诺",
        "upright_love": "浪漫的追求者出现，用心呵护感情，温柔而坚定",
        "reversed_love": "嘴上说爱却不付诸行动，花言巧语不真诚，逃避承诺",
        "upright_work": "带着热爱做事，用创意推动项目，追求理想工作",
        "reversed_work": "过于理想化不切实际，说得多做得少",
    },
    {
        "number": 13,
        "name": "圣杯皇后 Queen of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "温柔共情、直觉敏锐、情感丰富、关怀体贴",
        "reversed": "情绪过载、过度敏感、忽视自我、情感依赖",
        "upright_love": "深情且体贴的伴侣，直觉感知对方需求，温暖治愈",
        "reversed_love": "过度付出忽视自己需求，情绪化让关系疲惫",
        "upright_work": "用同理心处理团队关系，直觉判断准确，创意工作出色",
        "reversed_work": "情绪影响判断力，过度在意他人看法，忽视自身需求",
    },
    {
        "number": 14,
        "name": "圣杯国王 King of Cups",
        "suit": "圣杯",
        "element": "水",
        "emoji": "🏆",
        "upright": "情感成熟、冷静理性、包容大度、情商高手",
        "reversed": "情感压抑、表面冷静内心波涛、情绪操控、逃避感受",
        "upright_love": "成熟稳重的伴侣，理性处理感情问题，包容且深情",
        "reversed_love": "压抑真实感受不愿表达，用冷漠掩饰内心波动",
        "upright_work": "高情商领导，善于平衡团队情绪，冷静决策",
        "reversed_work": "表面冷静内心焦虑，用情绪操控团队，不愿表达真实想法",
    },
]
