"""
大阿卡纳 - Major Arcana (22张)
代表人生重大课题与灵魂旅程
"""

MAJOR_ARCANA = [
    {
        "number": 0,
        "name": "愚人 The Fool",
        "suit": "大阿卡纳",
        "element": "风",
        "emoji": "🃏",
        "upright": "自由洒脱、天真勇敢、潜能无限、活在当下",
        "reversed": "鲁莽冲动、不负责任、浮躁愚昧、风险失控",
        "upright_love": "重拾新鲜感，勇敢开启新可能，纯粹心动，不被过去束缚",
        "reversed_love": "冲动引发矛盾，轻率择偶，空想不落地，忽视彼此需求",
        "upright_work": "主动突破舒适区，怀揣热情启程，开放接受新机会",
        "reversed_work": "鲁莽犯错，盲目投入未做调研，轻率做选择浪费时间",
    },
    {
        "number": 1,
        "name": "魔术师 The Magician",
        "suit": "大阿卡纳",
        "element": "风",
        "emoji": "🎩",
        "upright": "创造力、行动力、资源整合、自信掌控",
        "reversed": "欺骗操控、能力不足、缺乏规划、眼高手低",
        "upright_love": "主动表达心意，用行动经营感情，魅力吸引对方",
        "reversed_love": "花言巧语不真诚，感情中有隐瞒或操控倾向",
        "upright_work": "整合资源推进项目，展现专业能力，把想法变现",
        "reversed_work": "计划不周导致失败，过度自信忽略细节，纸上谈兵",
    },
    {
        "number": 2,
        "name": "女祭司 The High Priestess",
        "suit": "大阿卡纳",
        "element": "水",
        "emoji": "🌙",
        "upright": "直觉敏锐、内在智慧、神秘感、静待时机",
        "reversed": "忽视直觉、信息不明、过度敏感、封闭内心",
        "upright_love": "倾听内心声音，感情中保持神秘与吸引力，直觉引导方向",
        "reversed_love": "猜疑过多，隐藏真实感受，过度敏感导致误会",
        "upright_work": "用直觉判断方向，深入研究后再行动，保持冷静观察",
        "reversed_work": "信息不足急于决策，忽视内心警示，过度犹豫不决",
    },
    {
        "number": 3,
        "name": "女皇 The Empress",
        "suit": "大阿卡纳",
        "element": "土",
        "emoji": "👑",
        "upright": "丰盛富足、母性关怀、创造力、感官享受",
        "reversed": "过度溺爱、依赖他人、创造力受阻、物质匮乏",
        "upright_love": "感情甜蜜滋养，充满爱与关怀，关系稳定成长",
        "reversed_love": "过度付出失去自我，控制欲强，感情中缺乏安全感",
        "upright_work": "创意丰富收获成果，团队氛围和谐，项目进展顺利",
        "reversed_work": "工作缺乏动力，创意枯竭，过度依赖他人支持",
    },
    {
        "number": 4,
        "name": "皇帝 The Emperor",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "🏰",
        "upright": "权威领导、秩序稳定、理性果断、责任担当",
        "reversed": "专制独裁、过度控制、僵化固执、逃避责任",
        "upright_love": "给予安全感，愿意承担责任，关系有明确方向",
        "reversed_love": "控制欲过强，不尊重对方意见，感情中过于强势",
        "upright_work": "展现领导力，制定清晰计划，团队有序推进",
        "reversed_work": "管理方式僵化，过度独断，不听取团队建议",
    },
    {
        "number": 5,
        "name": "教皇 The Hierophant",
        "suit": "大阿卡纳",
        "element": "土",
        "emoji": "⛪",
        "upright": "传统智慧、精神导师、遵循规则、信仰指引",
        "reversed": "打破常规、质疑权威、教条束缚、固步自封",
        "upright_love": "传统稳定的关系，得到长辈祝福，共同价值观",
        "reversed_love": "被传统观念束缚，三观不合，对关系有非主流想法",
        "upright_work": "遵循行业规范，向前辈学习，走稳健路线",
        "reversed_work": "不愿遵守规则，与上级理念冲突，想走非传统路线",
    },
    {
        "number": 6,
        "name": "恋人 The Lovers",
        "suit": "大阿卡纳",
        "element": "风",
        "emoji": "💕",
        "upright": "爱情选择、价值观契合、和谐结合、心灵连接",
        "reversed": "价值观冲突、感情失衡、选择困难、关系不和谐",
        "upright_love": "真挚的感情连接，灵魂伴侣，彼此吸引相互理解",
        "reversed_love": "三观不合矛盾频发，面临感情抉择，信任出现裂痕",
        "upright_work": "找到热爱的方向，合作伙伴默契，事业抉择清晰",
        "reversed_work": "合作关系出现分歧，职业选择困难，价值观不匹配",
    },
    {
        "number": 7,
        "name": "战车 The Chariot",
        "suit": "大阿卡纳",
        "element": "水",
        "emoji": "🏎️",
        "upright": "意志坚定、勇往直前、克服困难、掌控方向",
        "reversed": "方向迷失、失去控制、急躁冲动、内心冲突",
        "upright_love": "积极追求所爱，克服感情障碍，关系向前推进",
        "reversed_love": "感情方向不明，两人步调不一致，控制欲引发冲突",
        "upright_work": "目标明确全力以赴，克服工作障碍，取得突破性进展",
        "reversed_work": "努力方向错误，急于求成适得其反，项目失控",
    },
    {
        "number": 8,
        "name": "力量 Strength",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "🦁",
        "upright": "内在力量、温柔坚韧、勇气耐心、自我克制",
        "reversed": "自我怀疑、缺乏勇气、情绪失控、内心脆弱",
        "upright_love": "用温柔化解矛盾，感情中展现包容与耐心",
        "reversed_love": "情绪化处理问题，缺乏安全感，在感情中迷失自我",
        "upright_work": "以柔克刚处理难题，坚持不懈终有成果",
        "reversed_work": "遇困难就退缩，缺乏自信影响表现，内耗严重",
    },
    {
        "number": 9,
        "name": "隐士 The Hermit",
        "suit": "大阿卡纳",
        "element": "土",
        "emoji": "🏔️",
        "upright": "独处反思、内在探索、寻找真理、精神导师",
        "reversed": "自我封闭、过度孤僻、逃避社交、迷失方向",
        "upright_love": "需要独处思考感情方向，内省后更清楚自己要什么",
        "reversed_love": "过度封闭拒绝沟通，孤独感强烈却不愿走出去",
        "upright_work": "深入钻研专业，独立思考找到解决方案",
        "reversed_work": "闭门造车脱离实际，过度独处影响团队协作",
    },
    {
        "number": 10,
        "name": "命运之轮 Wheel of Fortune",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "🎡",
        "upright": "命运转折、好运降临、因果循环、顺势而为",
        "reversed": "时机未到、运势低迷、抗拒变化、坏运气、失控感",
        "upright_love": "感情迎来转折点，缘分到来，关系进入新阶段",
        "reversed_love": "感情时机未到，遇到低谷期需要耐心等待，缘分还在路上",
        "upright_work": "事业迎来机遇，贵人相助，顺势而为会有好结果",
        "reversed_work": "时机尚未成熟，运势暂时低迷，计划受阻需要等待和调整",
    },
    {
        "number": 11,
        "name": "正义 Justice",
        "suit": "大阿卡纳",
        "element": "风",
        "emoji": "⚖️",
        "upright": "公平正义、因果报应、理性判断、承担后果",
        "reversed": "不公平待遇、逃避责任、判断偏差、失去平衡",
        "upright_love": "公平对等的关系，共同承担责任，做出理性选择",
        "reversed_love": "感情中付出不对等，不愿面对真相，逃避问题",
        "upright_work": "凭实力获得认可，合同签订顺利，公平竞争胜出",
        "reversed_work": "遭遇不公平对待，法律纠纷，决策失误需承担后果",
    },
    {
        "number": 12,
        "name": "倒吊人 The Hanged Man",
        "suit": "大阿卡纳",
        "element": "水",
        "emoji": "🙃",
        "upright": "换个角度看、牺牲奉献、暂停等待、灵性觉醒",
        "reversed": "无意义的牺牲、拒绝改变、拖延逃避、白费功夫",
        "upright_love": "放下执念换个角度理解对方，牺牲小我成全关系",
        "reversed_love": "一味付出不被珍惜，拒绝改变固有模式，感情停滞",
        "upright_work": "暂停脚步重新审视，换思路找到突破口",
        "reversed_work": "拖延不决错过时机，无意义的等待浪费时间",
    },
    {
        "number": 13,
        "name": "死神 Death",
        "suit": "大阿卡纳",
        "element": "水",
        "emoji": "💀",
        "upright": "结束与重生、彻底转变、放下过去、新的开始",
        "reversed": "抗拒改变、恐惧结束、停滞不前、无法放手",
        "upright_love": "旧关系结束迎来新开始，放下过去才能拥抱新爱情",
        "reversed_love": "无法放下前任，恐惧感情变化，明知该结束却拖着",
        "upright_work": "旧模式淘汰转型升级，结束不适合的工作迎来新机遇",
        "reversed_work": "抗拒公司变革，守着没前途的岗位不愿改变",
    },
    {
        "number": 14,
        "name": "节制 Temperance",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "🏺",
        "upright": "平衡调和、耐心温和、中庸之道、自我疗愈",
        "reversed": "失去平衡、过度极端、缺乏耐心、内心冲突",
        "upright_love": "感情和谐平衡，彼此磨合调和，关系走向成熟",
        "reversed_love": "感情失衡一方付出过多，缺乏耐心导致争吵，极端情绪",
        "upright_work": "工作生活平衡，团队协调顺畅，稳步前进",
        "reversed_work": "工作节奏失调，过度加班或懈怠，团队配合不默契",
    },
    {
        "number": 15,
        "name": "恶魔 The Devil",
        "suit": "大阿卡纳",
        "element": "土",
        "emoji": "😈",
        "upright": "欲望束缚、物质诱惑、依赖执着、阴暗面",
        "reversed": "挣脱束缚、正视阴暗面、重获自由、放下执念",
        "upright_love": "被欲望驱动的关系，不健康的依赖，明知有害却无法脱身",
        "reversed_love": "认清不健康的关系模式，鼓起勇气断开束缚",
        "upright_work": "被工作绑架失去自由，为金钱妥协底线，职场潜规则",
        "reversed_work": "摆脱不良工作环境，拒绝诱惑回归正轨",
    },
    {
        "number": 16,
        "name": "塔 The Tower",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "🗼",
        "upright": "突然崩塌、颠覆认知、破旧立新、真相揭露",
        "reversed": "逃避灾难、抗拒改变、延迟崩塌、内心恐惧",
        "upright_love": "感情遭受突然冲击，真相暴露，旧有关系模式被打破",
        "reversed_love": "明知问题严重却粉饰太平，拖延面对迟早要来的崩塌",
        "upright_work": "突发变故打乱计划，裁员或项目取消，被迫重新开始",
        "reversed_work": "预感危机但不愿面对，公司暗藏问题迟早爆发",
    },
    {
        "number": 17,
        "name": "星星 The Star",
        "suit": "大阿卡纳",
        "element": "风",
        "emoji": "⭐",
        "upright": "希望重燃、灵感涌现、平静治愈、美好愿景",
        "reversed": "失去希望、灵感枯竭、信心不足、脱离现实",
        "upright_love": "感情充满希望，心灵治愈，对未来有美好期待",
        "reversed_love": "对爱情失去信心，过于理想化导致失望",
        "upright_work": "灵感爆发创意涌现，前景光明，得到认可鼓励",
        "reversed_work": "缺乏方向感，目标不切实际，创作瓶颈",
    },
    {
        "number": 18,
        "name": "月亮 The Moon",
        "suit": "大阿卡纳",
        "element": "水",
        "emoji": "🌕",
        "upright": "潜意识、幻象迷雾、不安恐惧、直觉梦境",
        "reversed": "走出迷雾、真相浮现、克服恐惧、理性回归",
        "upright_love": "感情中有不安和猜疑，信息不透明，被幻觉迷惑",
        "reversed_love": "误会澄清真相大白，走出感情困惑，恢复理性",
        "upright_work": "职场信息不明朗，有隐藏的竞争或欺骗，谨慎决策",
        "reversed_work": "迷雾散去看清局势，走出困惑期，恢复判断力",
    },
    {
        "number": 19,
        "name": "太阳 The Sun",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "☀️",
        "upright": "光明灿烂、乐观自信、成功喜悦、活力满满",
        "reversed": "短暂阴霾、过度乐观、自负虚荣、延迟成功",
        "upright_love": "感情阳光甜蜜，坦诚相待，充满快乐与活力",
        "reversed_love": "快乐中有隐忧，过度表面化忽视深层问题",
        "upright_work": "事业成功曙光到来，获得认可奖励，充满成就感",
        "reversed_work": "成功来得比预期慢，过度自信忽略风险",
    },
    {
        "number": 20,
        "name": "审判 Judgement",
        "suit": "大阿卡纳",
        "element": "火",
        "emoji": "📯",
        "upright": "觉醒重生、反思总结、使命召唤、重大决定",
        "reversed": "逃避反省、拒绝成长、错过机会、自我否定",
        "upright_love": "重新审视感情，做出决定性选择，关系迎来新生",
        "reversed_love": "不愿面对感情问题，错过修复机会，自我逃避",
        "upright_work": "重大职业转折期，听从内心使命，做出关键决策",
        "reversed_work": "犹豫不决错过好机会，不愿反省过去的失误",
    },
    {
        "number": 21,
        "name": "世界 The World",
        "suit": "大阿卡纳",
        "element": "土",
        "emoji": "🌍",
        "upright": "圆满完成、功德圆满、整合统一、新旅程起点",
        "reversed": "尚未完成、缺少闭合感、拖延收尾、目标未达",
        "upright_love": "感情达到圆满状态，彼此成就，开启人生新篇章",
        "reversed_love": "感情差最后一步，有遗憾未解决，尚未达到理想状态",
        "upright_work": "项目圆满收官，达成目标获得成就，准备迎接新挑战",
        "reversed_work": "项目收尾拖延，差临门一脚，目标尚未完全实现",
    },
]
