"""
星币牌组 - Pentacles (14张)
元素：土 | 代表：物质、稳定、务实、财富
对应星座：金牛、处女、摩羯
"""

PENTACLES = [
    {
        "number": 1,
        "name": "星币王牌 Ace of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "新的财运、物质机遇、务实开端、丰盛潜力",
        "reversed": "错失良机、财务损失、计划落空、贪心不足",
        "upright_love": "稳定踏实的新感情，物质基础良好，关系有安全感",
        "reversed_love": "因物质问题影响感情，过于看重金钱忽视情感",
        "upright_work": "新的赚钱机会，项目有盈利前景，事业开局好",
        "reversed_work": "投资失利错过机会，项目资金不足，规划不切实际",
    },
    {
        "number": 2,
        "name": "星币二 Two of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "灵活平衡、多任务处理、适应变化、资源调配",
        "reversed": "失去平衡、顾此失彼、财务混乱、压力过大",
        "upright_love": "在感情和其他事务间灵活平衡，适应关系中的变化",
        "reversed_love": "工作太忙顾不上感情，生活失衡影响关系",
        "upright_work": "同时处理多个任务游刃有余，灵活应对变化",
        "reversed_work": "事情太多顾此失彼，财务管理混乱，压力山大",
    },
    {
        "number": 3,
        "name": "星币三 Three of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "团队协作、专业技能、精益求精、获得认可",
        "reversed": "合作不畅、技能不足、敷衍了事、不被认可",
        "upright_love": "共同经营关系，彼此配合默契，一起建设未来",
        "reversed_love": "感情中缺乏配合，各做各的没有共同目标",
        "upright_work": "团队协作出色，专业能力被认可，精品项目",
        "reversed_work": "团队配合差效率低，工作质量不达标，缺乏专业性",
    },
    {
        "number": 4,
        "name": "星币四 Four of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "守财节俭、安全感、控制资源、保守稳定",
        "reversed": "过度吝啬、放手释放、贪婪执着、财务不安",
        "upright_love": "感情中追求安全稳定，牢牢守住已有的关系",
        "reversed_love": "控制欲太强让对方窒息，或终于学会放手",
        "upright_work": "财务管理稳健，保守策略守住成果",
        "reversed_work": "过于保守错失发展机会，抠门影响业务拓展",
    },
    {
        "number": 5,
        "name": "星币五 Five of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "经济困难、物质匮乏、被排斥孤立、身心俱疲",
        "reversed": "困境好转、找到援助、经济恢复、走出低谷",
        "upright_love": "感情因现实问题受困，经济压力影响关系，感到被抛弃",
        "reversed_love": "共同度过困难期，找到解决物质问题的方法",
        "upright_work": "经济困难失业或降薪，事业低谷期，资源匮乏",
        "reversed_work": "经济状况开始好转，找到新的收入来源，走出困境",
    },
    {
        "number": 6,
        "name": "星币六 Six of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "慷慨给予、公平分配、互帮互助、施与受平衡",
        "reversed": "施舍感、不公平交换、有条件的帮助、债务",
        "upright_love": "感情中互相付出平等给予，慷慨对待彼此",
        "reversed_love": "付出不对等有施舍感，帮助附带条件，关系不平等",
        "upright_work": "获得资助或加薪，公平的利益分配，贵人帮助",
        "reversed_work": "薪资不公平，帮助别人却没有回报，欠人情债",
    },
    {
        "number": 7,
        "name": "星币七 Seven of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "耐心等待、评估成果、长期投资、反思调整",
        "reversed": "急于求成、回报不足、方向错误、浪费投入",
        "upright_love": "耐心经营感情等待开花结果，评估关系是否值得继续",
        "reversed_love": "对感情付出感到不值得，急于看到回报缺乏耐心",
        "upright_work": "长期投入开始见效，评估项目方向，耐心等待回报",
        "reversed_work": "投入多回报少感到失望，可能需要调整方向",
    },
    {
        "number": 8,
        "name": "星币八 Eight of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "勤奋努力、精益求精、技能提升、专注钻研",
        "reversed": "敷衍塞责、缺乏热情、重复无聊、不思进取",
        "upright_love": "用心经营感情细水长流，不断提升自己吸引对方",
        "reversed_love": "感情变得乏味，不愿花心思经营，敷衍了事",
        "upright_work": "专注钻研提升技能，勤奋工作精益求精，匠人精神",
        "reversed_work": "工作敷衍没有热情，重复劳动感到无聊，不想进步",
    },
    {
        "number": 9,
        "name": "星币九 Nine of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "财务自由、独立自足、享受成果、品质生活",
        "reversed": "过度消费、依赖他人、虚荣攀比、财务不独立",
        "upright_love": "独立自信的状态最有吸引力，不依赖他人也过得很好",
        "reversed_love": "经济上依赖伴侣失去独立性，用物质填补情感空缺",
        "upright_work": "事业有成财务自由，享受努力带来的成果",
        "reversed_work": "过度消费入不敷出，工作成果被他人占有",
    },
    {
        "number": 10,
        "name": "星币十 Ten of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "家族传承、财富积累、长久稳定、世代繁荣",
        "reversed": "家庭纷争、遗产纠纷、根基不稳、传承断裂",
        "upright_love": "感情走向婚姻家庭，长久稳定的关系，家族认可",
        "reversed_love": "家庭矛盾影响感情，财产纠纷，婆媳或家族问题",
        "upright_work": "事业稳固长期收益，公司根基扎实，留下长久成果",
        "reversed_work": "公司根基出问题，合伙人纷争，长期规划落空",
    },
    {
        "number": 11,
        "name": "星币侍从 Page of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "踏实学习、新的理财计划、务实目标、勤奋上进",
        "reversed": "眼高手低、不切实际、缺乏行动、浪费资源",
        "upright_love": "踏实认真对待感情，用实际行动表达爱意",
        "reversed_love": "光说不做承诺落空，感情中不够务实",
        "upright_work": "认真学习新技能，制定务实目标，踏实肯干",
        "reversed_work": "目标不切实际，学习没有耐心，眼高手低",
    },
    {
        "number": 12,
        "name": "星币骑士 Knight of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "稳扎稳打、可靠负责、坚持不懈、踏实前行",
        "reversed": "过于死板、进展缓慢、固执不变通、懒惰拖延",
        "upright_love": "可靠踏实的伴侣，虽不浪漫但给人安全感，负责任",
        "reversed_love": "感情中太过无聊死板，缺乏激情和浪漫，不懂变通",
        "upright_work": "稳扎稳打推进工作，可靠负责完成任务",
        "reversed_work": "工作效率太低进展缓慢，方法死板不懂创新",
    },
    {
        "number": 13,
        "name": "星币皇后 Queen of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "贤惠能干、理财高手、温暖务实、生活品质",
        "reversed": "过度操劳、忽视自我、物质焦虑、工作狂",
        "upright_love": "温暖体贴会照顾人，把生活经营得有声有色",
        "reversed_love": "为家庭过度操劳忽视自己，或过于在意物质条件",
        "upright_work": "理财管理能力出色，把工作和生活都安排得井井有条",
        "reversed_work": "工作狂忽视健康和家庭，为钱焦虑影响状态",
    },
    {
        "number": 14,
        "name": "星币国王 King of Pentacles",
        "suit": "星币",
        "element": "土",
        "emoji": "💰",
        "upright": "财富成就、商业头脑、稳重可靠、物质丰盛",
        "reversed": "贪婪拜金、守财奴、投资失败、物质至上",
        "upright_love": "给予物质安全感和稳定生活，成熟可靠的伴侣",
        "reversed_love": "用金钱衡量感情，工作太忙忽视伴侣，拜金主义",
        "upright_work": "事业巅峰财务丰厚，商业决策英明，值得信赖的领导",
        "reversed_work": "过度追求利润不择手段，投资失败损失惨重",
    },
]
