"""
宝剑牌组 - Swords (14张)
元素：风 | 代表：思维、沟通、逻辑、冲突
对应星座：双子、天秤、水瓶
"""

SWORDS = [
    {
        "number": 1,
        "name": "宝剑王牌 Ace of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "真相大白、思维清晰、突破性想法、正义胜利",
        "reversed": "思维混乱、真相被掩盖、沟通障碍、判断失误",
        "upright_love": "看清感情真相，理性面对关系问题，清晰的沟通",
        "reversed_love": "感情中有误解和隐瞒，沟通不畅真相不明",
        "upright_work": "头脑清晰找到解决方案，新想法突破瓶颈",
        "reversed_work": "思路混乱判断失误，信息不全导致错误决策",
    },
    {
        "number": 2,
        "name": "宝剑二 Two of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "左右为难、僵持不下、逃避选择、内心矛盾",
        "reversed": "打破僵局、做出决定、信息浮现、不再逃避",
        "upright_love": "感情中左右为难，回避核心问题，两难抉择",
        "reversed_love": "终于面对感情问题做出选择，打破僵持状态",
        "upright_work": "工作中面临两难选择，犹豫不决拖延决策",
        "reversed_work": "获得新信息打破僵局，终于做出工作上的决定",
    },
    {
        "number": 3,
        "name": "宝剑三 Three of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "心碎伤痛、背叛打击、悲伤难过、真相刺痛",
        "reversed": "伤痛愈合、原谅释怀、走出悲伤、自我修复",
        "upright_love": "感情遭受重大打击，背叛或分手的痛苦，心碎时刻",
        "reversed_love": "从感情伤痛中恢复，选择原谅或释怀，开始愈合",
        "upright_work": "工作中受到打击，被同事背后议论，项目失败的痛",
        "reversed_work": "从职场挫折中恢复，放下怨恨重新出发",
    },
    {
        "number": 4,
        "name": "宝剑四 Four of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "休息恢复、暂停充电、冥想反思、养精蓄锐",
        "reversed": "急于行动、无法放松、焦虑不安、强撑硬扛",
        "upright_love": "感情需要冷静期，给彼此空间思考，休息后再决定",
        "reversed_love": "无法冷静下来，焦虑不安急于解决问题反而更糟",
        "upright_work": "需要休息恢复精力，暂停项目重新规划",
        "reversed_work": "不懂休息强撑工作，焦虑导致效率低下，需要放慢",
    },
    {
        "number": 5,
        "name": "宝剑五 Five of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "冲突争执、赢了面子输了里子、不择手段、自私",
        "reversed": "和解认错、放下争斗、接受失败、吸取教训",
        "upright_love": "感情中激烈争吵互相伤害，赢了吵架输了感情",
        "reversed_love": "双方放下争执选择和解，承认错误修复关系",
        "upright_work": "职场争斗不择手段，同事间恶性竞争，赢了项目失了人心",
        "reversed_work": "放下职场纷争，承认失误寻求和解，不再恶性竞争",
    },
    {
        "number": 6,
        "name": "宝剑六 Six of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "离开困境、过渡转变、走向平静、带着伤前行",
        "reversed": "无法脱身、原地打转、抗拒改变、旧问题重现",
        "upright_love": "离开不健康的关系走向新生活，虽有伤但在前进",
        "reversed_love": "想离开却走不了，反复纠缠，旧感情问题重现",
        "upright_work": "离开不好的工作环境，过渡期虽难但在变好",
        "reversed_work": "想换工作却走不出去，被困在不满意的岗位上",
    },
    {
        "number": 7,
        "name": "宝剑七 Seven of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "欺骗策略、偷偷行动、小聪明、不诚实",
        "reversed": "谎言被揭穿、良心发现、坦诚面对、自欺欺人",
        "upright_love": "感情中有欺骗或隐瞒，一方在偷偷做不诚实的事",
        "reversed_love": "谎言被揭穿真相大白，或者良心发现选择坦诚",
        "upright_work": "职场中有人耍小聪明，窃取成果或暗中算计",
        "reversed_work": "不诚实的行为被发现，或决定不再走捷径回归正道",
    },
    {
        "number": 8,
        "name": "宝剑八 Eight of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "自我囚禁、思维受困、无力感、看不到出路",
        "reversed": "解放自己、打破限制、换个角度、重获自由",
        "upright_love": "在感情中感到被困住，自我限制看不到出路",
        "reversed_love": "意识到束缚来自自己，打破思维局限重获自由",
        "upright_work": "工作中感到无能为力，被困在不喜欢的处境中",
        "reversed_work": "换个角度看到出路，突破自我设限，重拾信心",
    },
    {
        "number": 9,
        "name": "宝剑九 Nine of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "焦虑失眠、噩梦恐惧、过度担忧、心理压力",
        "reversed": "走出焦虑、面对恐惧、寻求帮助、最坏的已过去",
        "upright_love": "对感情过度焦虑和担忧，失眠想太多，恐惧不安",
        "reversed_love": "开始走出感情焦虑，意识到很多担忧是多余的",
        "upright_work": "工作压力导致焦虑失眠，对前途过度恐慌",
        "reversed_work": "走出工作焦虑期，寻求帮助或意识到没那么糟",
    },
    {
        "number": 10,
        "name": "宝剑十 Ten of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "彻底结束、最痛的底部、背叛打击、否极泰来",
        "reversed": "最坏已过、开始恢复、拒绝放手、苦难延续",
        "upright_love": "感情走到尽头彻底结束，最痛的时刻但也是新开始",
        "reversed_love": "感情虽然很痛但拒绝接受结束，或最坏的已经过去",
        "upright_work": "项目彻底失败或被裁员，到了最低谷但否极泰来",
        "reversed_work": "最困难的时期正在过去，或不愿接受失败继续硬撑",
    },
    {
        "number": 11,
        "name": "宝剑侍从 Page of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "好奇心强、思维活跃、善于观察、新想法",
        "reversed": "八卦多嘴、尖酸刻薄、狡猾不诚实、思维散乱",
        "upright_love": "对感情充满好奇和探索欲，用理性分析关系",
        "reversed_love": "在感情中话太多管太宽，八卦或尖酸的言语伤人",
        "upright_work": "善于调研分析，提出新颖观点，学习能力强",
        "reversed_work": "办公室八卦制造者，话多但不靠谱，想法散乱不落地",
    },
    {
        "number": 12,
        "name": "宝剑骑士 Knight of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "思维敏捷、直言不讳、雷厉风行、追求真相",
        "reversed": "言语伤人、冲动莽撞、不顾后果、思维偏激",
        "upright_love": "直接表达心意不拐弯抹角，快速推进关系",
        "reversed_love": "说话太直伤害对方，冲动之下说出后悔的话",
        "upright_work": "快速推进项目，直言不讳指出问题，效率极高",
        "reversed_work": "做事不考虑后果，言语冒犯同事，冲动决策",
    },
    {
        "number": 13,
        "name": "宝剑皇后 Queen of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "独立理性、洞察力强、坦诚直率、经验智慧",
        "reversed": "冷漠尖刻、过于挑剔、固执己见、情感隔离",
        "upright_love": "理性看待感情，不被情绪左右，有清晰的底线和标准",
        "reversed_love": "对伴侣过于挑剔苛刻，用冷漠推开别人保护自己",
        "upright_work": "专业能力强，独立解决问题，洞察力帮助做出正确判断",
        "reversed_work": "过于苛刻难以合作，冷漠的态度影响团队关系",
    },
    {
        "number": 14,
        "name": "宝剑国王 King of Swords",
        "suit": "宝剑",
        "element": "风",
        "emoji": "⚔️",
        "upright": "理性权威、公正严明、逻辑清晰、决断果敢",
        "reversed": "冷酷无情、滥用权力、独断偏见、操控他人",
        "upright_love": "用理性守护感情，公正处理关系问题，值得信赖",
        "reversed_love": "感情中过于冷酷理性，缺乏温度，用道理压人",
        "upright_work": "卓越的决策者，逻辑清晰公正管理，解决复杂问题",
        "reversed_work": "滥用职权独断专行，冷酷管理不近人情，以权谋私",
    },
]
