"""
权杖牌组 - Wands (14张)
元素：火 | 代表：行动、热情、勇气、创造力
对应星座：白羊、狮子、射手
"""

WANDS = [
    {
        "number": 1,
        "name": "权杖王牌 Ace of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "新的开始、灵感迸发、创造力、充满热情",
        "reversed": "缺乏动力、灵感枯竭、延迟启动、方向不明",
        "upright_love": "一见钟情的心动，新恋情的萌芽，感情中注入新活力",
        "reversed_love": "对感情提不起兴趣，新关系迟迟没有进展",
        "upright_work": "新项目新机遇，充满干劲，灵感爆棚想法多",
        "reversed_work": "项目启动困难，缺乏方向和动力，创意受阻",
    },
    {
        "number": 2,
        "name": "权杖二 Two of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "规划未来、做出选择、远见卓识、掌握主动权",
        "reversed": "恐惧未知、缺乏规划、犹豫不决、安于现状",
        "upright_love": "主动规划感情方向，对关系有清晰愿景",
        "reversed_love": "对感情未来感到迷茫，害怕迈出下一步",
        "upright_work": "制定长远规划，有远见地布局事业，考虑新发展",
        "reversed_work": "害怕改变不敢规划，局限于眼前安逸不愿突破",
    },
    {
        "number": 3,
        "name": "权杖三 Three of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "拓展视野、等待成果、放眼长远、合作共赢",
        "reversed": "眼界狭窄、成果延迟、计划受阻、缺乏远见",
        "upright_love": "感情进入新阶段，异地恋有进展，共同展望未来",
        "reversed_love": "感情发展不如预期，异地带来的困扰，缺乏共同目标",
        "upright_work": "项目初见成效，业务拓展顺利，放眼更大市场",
        "reversed_work": "扩展计划受挫，回报来得比预期慢，视野受限",
    },
    {
        "number": 4,
        "name": "权杖四 Four of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "庆祝成功、和谐稳定、归属感、里程碑",
        "reversed": "缺乏归属、不稳定感、庆祝被推迟、内部矛盾",
        "upright_love": "感情稳定甜蜜，订婚或同居，关系得到祝福",
        "reversed_love": "关系缺乏安全感，重要节点被推迟，家庭压力",
        "upright_work": "项目阶段性成功，团队庆祝，工作环境和谐",
        "reversed_work": "团队氛围紧张，成果未被认可，缺乏归属感",
    },
    {
        "number": 5,
        "name": "权杖五 Five of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "竞争冲突、意见分歧、挑战对抗、各抒己见",
        "reversed": "逃避冲突、内心挣扎、达成妥协、竞争退出",
        "upright_love": "感情中争吵不断，各执己见互不相让，竞争对手出现",
        "reversed_love": "避免正面冲突冷处理，双方开始妥协，竞争结束",
        "upright_work": "职场竞争激烈，团队意见不统一，项目面临挑战",
        "reversed_work": "竞争压力缓解，团队达成共识，或选择退出竞争",
    },
    {
        "number": 6,
        "name": "权杖六 Six of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "胜利凯旋、获得认可、自信荣耀、公众赞誉",
        "reversed": "失败挫折、缺乏认可、骄傲自大、名声受损",
        "upright_love": "感情顺利令人羡慕，得到朋友祝福，关系中有成就感",
        "reversed_love": "感情不被看好，虚荣心作祟，过于在意他人眼光",
        "upright_work": "获得晋升或嘉奖，项目成功被认可，业绩突出",
        "reversed_work": "努力不被认可，项目失利，因骄傲导致失误",
    },
    {
        "number": 7,
        "name": "权杖七 Seven of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "坚守立场、捍卫成果、勇敢面对挑战、不退缩",
        "reversed": "放弃抵抗、压力过大、失去优势、退缩妥协",
        "upright_love": "为感情坚定立场，面对外界压力不退缩",
        "reversed_love": "在压力下放弃感情，无法继续坚持，筋疲力尽",
        "upright_work": "面对竞争坚守阵地，捍卫自己的成果和地位",
        "reversed_work": "竞争中落败，扛不住压力选择退让，失去优势",
    },
    {
        "number": 8,
        "name": "权杖八 Eight of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "快速推进、信息传递、旅行出差、事情加速",
        "reversed": "延迟阻碍、信息混乱、计划推迟、仓促行事",
        "upright_love": "感情快速发展，异地恋迎来好消息，关系加速推进",
        "reversed_love": "沟通不畅消息延迟，感情进展缓慢，误会未解",
        "upright_work": "项目快速推进，出差或调动，效率大增",
        "reversed_work": "项目延期，信息传达混乱，计划被打乱",
    },
    {
        "number": 9,
        "name": "权杖九 Nine of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "坚持到底、警惕防备、最后的考验、韧性",
        "reversed": "精疲力尽、放弃坚持、过度防备、偏执多疑",
        "upright_love": "感情经历考验但不放弃，保持警惕保护关系",
        "reversed_love": "在感情中身心俱疲，过度防备不信任对方",
        "upright_work": "最后冲刺阶段，虽然疲惫但坚持就是胜利",
        "reversed_work": "工作压力到极限想要放弃，过度紧张影响状态",
    },
    {
        "number": 10,
        "name": "权杖十 Ten of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "负担沉重、责任过多、硬撑到底、压力巨大",
        "reversed": "卸下重担、学会放手、委托他人、减轻压力",
        "upright_love": "感情成为负担，付出过多身心疲惫，关系压力大",
        "reversed_love": "学会放手不再硬撑，重新分配感情中的责任",
        "upright_work": "工作量超负荷，一个人扛太多，需要学会分担",
        "reversed_work": "开始把任务分给别人，减轻工作负担，学会说不",
    },
    {
        "number": 11,
        "name": "权杖侍从 Page of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "热情探索、好奇心旺盛、新消息、冒险精神",
        "reversed": "三分钟热度、缺乏耐心、坏消息、鲁莽冲动",
        "upright_love": "对新感情充满好奇和热情，大胆追求心动的人",
        "reversed_love": "对感情三分钟热度，新鲜感过后失去兴趣",
        "upright_work": "积极学习新技能，对新项目充满热情，收到好消息",
        "reversed_work": "做事缺乏耐心虎头蛇尾，冲动决策缺乏思考",
    },
    {
        "number": 12,
        "name": "权杖骑士 Knight of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "行动力强、冒险精神、热情澎湃、勇往直前",
        "reversed": "急躁冲动、方向迷失、热情消退、鲁莽行事",
        "upright_love": "热烈追求轰轰烈烈的爱情，充满激情和冒险",
        "reversed_love": "感情来得快去得也快，冲动之下做出后悔的决定",
        "upright_work": "雷厉风行推进工作，行动力爆棚，敢于冒险创新",
        "reversed_work": "做事急躁不够周全，换工作太频繁，缺乏稳定性",
    },
    {
        "number": 13,
        "name": "权杖皇后 Queen of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "自信魅力、热情大方、独立能干、社交达人",
        "reversed": "嫉妒自私、控制欲强、情绪化、缺乏自信",
        "upright_love": "在感情中自信且有魅力，热情经营关系，吸引力强",
        "reversed_love": "嫉妒心重控制对方，情绪化让关系紧张",
        "upright_work": "工作中散发领导魅力，社交能力强，人缘好",
        "reversed_work": "职场中嫉妒同事，控制欲影响团队，情绪化办事",
    },
    {
        "number": 14,
        "name": "权杖国王 King of Wands",
        "suit": "权杖",
        "element": "火",
        "emoji": "🔥",
        "upright": "领导魄力、远见卓识、大胆决断、激励他人",
        "reversed": "专横霸道、急功近利、独断专行、暴躁易怒",
        "upright_love": "在感情中有担当有魄力，引领关系走向更好的方向",
        "reversed_love": "大男子主义或过于强势，不考虑对方感受",
        "upright_work": "有远见的领导者，大胆决策带领团队突破",
        "reversed_work": "管理风格过于独断，急功近利忽略团队感受",
    },
]
